services:
  app:
    image: board-game-escape:latest
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DYNAMODB_ENDPOINT: http://192.168.4.51:8000
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      AWS_REGION: fakeRegion